export { default as isArray } from './isArray'
export { default as isDate } from './isDate'
export { default as isBoolean } from './isBoolean'
export { default as isBuffer } from './isBuffer'
export { default as isError } from './isError'
