name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    branches:
      - main
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      - name: Install deps
        run: pnpm install

      - name: Lint
        run: pnpm lint
      
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18.x, 20.x]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set node version to ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Setup
        run: npm i -g pnpm

      - name: Install
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Unit Test
        run: pnpm run test

  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18.x, 20.x]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set node version to ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Setup
        run: npm i -g pnpm

      - name: Install
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Unit Test
        run: pnpm run test

